export interface EmojiItem {
  emoji: string;
  name: string;
  keywords: string[];
}

export interface EmojiCategory {
  id: string;
  name: string;
  icon: string;
  emojis: EmojiItem[];
}

export const COMPLETE_EMOJI_DATA: EmojiCategory[] = [
  {
    id: 'smileys',
    name: 'Smileys & Emotion',
    icon: 'happy-outline',
    emojis: [
      { emoji: '😀', name: 'grinning face', keywords: ['smile', 'happy', 'grin', 'face'] },
      { emoji: '😃', name: 'grinning face with big eyes', keywords: ['happy', 'joy', 'smile'] },
      { emoji: '😄', name: 'grinning face with smiling eyes', keywords: ['happy', 'laugh', 'smile'] },
      { emoji: '😁', name: 'beaming face with smiling eyes', keywords: ['grin', 'smile', 'happy'] },
      { emoji: '😆', name: 'grinning squinting face', keywords: ['laugh', 'lol', 'haha', 'happy'] },
      { emoji: '😅', name: 'grinning face with sweat', keywords: ['sweat', 'phew', 'nervous', 'laugh'] },
      { emoji: '🤣', name: 'rolling on the floor laughing', keywords: ['rofl', 'lmao', 'lol', 'laugh'] },
      { emoji: '😂', name: 'face with tears of joy', keywords: ['cry', 'laugh', 'lol', 'joy'] },
      { emoji: '🙂', name: 'slightly smiling face', keywords: ['smile', 'ok', 'happy'] },
      { emoji: '🙃', name: 'upside-down face', keywords: ['silly', 'sarcasm', 'irony'] },
      { emoji: '🫠', name: 'melting face', keywords: ['melt', 'hot', 'awkward'] },
      { emoji: '😉', name: 'winking face', keywords: ['wink', 'flirt', 'joke'] },
      { emoji: '😊', name: 'smiling face with smiling eyes', keywords: ['blush', 'warm', 'happy'] },
      { emoji: '😇', name: 'smiling face with halo', keywords: ['angel', 'innocent', 'good'] },
      { emoji: '🥰', name: 'smiling face with hearts', keywords: ['love', 'crush', 'adore', 'heart'] },
      { emoji: '😍', name: 'smiling face with heart-eyes', keywords: ['love', 'crush', 'heart', 'adore'] },
      { emoji: '🤩', name: 'star-struck', keywords: ['excited', 'star', 'wow', 'amazing'] },
      { emoji: '😘', name: 'face blowing a kiss', keywords: ['kiss', 'love', 'flirt'] },
      { emoji: '😗', name: 'kissing face', keywords: ['kiss', 'love'] },
      { emoji: '😚', name: 'kissing face with closed eyes', keywords: ['kiss', 'sweet'] },
      { emoji: '😙', name: 'kissing face with smiling eyes', keywords: ['kiss', 'happy'] },
      { emoji: '🥲', name: 'smiling face with tear', keywords: ['proud', 'touched', 'gratitude'] },
      { emoji: '😋', name: 'face savoring food', keywords: ['yum', 'delicious', 'tasty', 'food'] },
      { emoji: '😛', name: 'face with tongue', keywords: ['tongue', 'silly', 'joke'] },
      { emoji: '😜', name: 'winking face with tongue', keywords: ['crazy', 'wink', 'silly'] },
      { emoji: '🤪', name: 'zany face', keywords: ['crazy', 'wild', 'party'] },
      { emoji: '😝', name: 'squinting face with tongue', keywords: ['tongue', 'playful', 'lol'] },
      { emoji: '🤑', name: 'money-mouth face', keywords: ['rich', 'money', 'dollar', 'cash'] },
      { emoji: '🤗', name: 'smiling face with open hands', keywords: ['hug', 'hugging', 'warm'] },
      { emoji: '🤭', name: 'face with hand over mouth', keywords: ['oops', 'giggle', 'secret'] },
      { emoji: '🫢', name: 'face with open eyes and hand over mouth', keywords: ['gasp', 'shock', 'surprise'] },
      { emoji: '🫣', name: 'face with peeking eye', keywords: ['peek', 'scared', 'shy', 'look'] },
      { emoji: '🤫', name: 'shushing face', keywords: ['quiet', 'secret', 'shh', 'silence'] },
      { emoji: '🤔', name: 'thinking face', keywords: ['think', 'idea', 'ponder', 'hmm'] },
      { emoji: '🫡', name: 'saluting face', keywords: ['salute', 'respect', 'yes', 'sir'] },
      { emoji: '🤐', name: 'zipper-mouth face', keywords: ['zip', 'secret', 'silent', 'quiet'] },
      { emoji: '🤨', name: 'face with raised eyebrow', keywords: ['skeptical', 'suspicious', 'doubt'] },
      { emoji: '😐', name: 'neutral face', keywords: ['meh', 'blank', 'ok'] },
      { emoji: '😑', name: 'expressionless face', keywords: ['poker', 'done', 'annoyed'] },
      { emoji: '😶', name: 'face without mouth', keywords: ['speechless', 'silent', 'quiet'] },
      { emoji: '🫥', name: 'dotted line face', keywords: ['invisible', 'hidden', 'fade'] },
      { emoji: '😶‍🌫️', name: 'face in clouds', keywords: ['fog', 'lost', 'cloud', 'daydream'] },
      { emoji: '😏', name: 'smirking face', keywords: ['smirk', 'flirt', 'sly', 'cool'] },
      { emoji: '😒', name: 'unamused face', keywords: ['annoyed', 'meh', 'dislike'] },
      { emoji: '🙄', name: 'face with rolling eyes', keywords: ['eyeroll', 'bored', 'annoyed'] },
      { emoji: '😬', name: 'grimacing face', keywords: ['yikes', 'awkward', 'cringe'] },
      { emoji: '😮‍💨', name: 'face exhaling', keywords: ['sigh', 'relief', 'tired', 'phew'] },
      { emoji: '🤥', name: 'lying face', keywords: ['lie', 'pinocchio', 'fake'] },
      { emoji: '😌', name: 'relieved face', keywords: ['calm', 'peace', 'relieved'] },
      { emoji: '😔', name: 'pensive face', keywords: ['sad', 'depressed', 'gloomy'] },
      { emoji: '😪', name: 'sleepy face', keywords: ['tired', 'sleep', 'rest'] },
      { emoji: '🤤', name: 'drooling face', keywords: ['drool', 'delicious', 'hungry'] },
      { emoji: '😴', name: 'sleeping face', keywords: ['sleep', 'zzz', 'night', 'tired'] },
      { emoji: '😷', name: 'face with medical mask', keywords: ['mask', 'sick', 'covid', 'ill'] },
      { emoji: '🤒', name: 'face with thermometer', keywords: ['sick', 'fever', 'ill'] },
      { emoji: '🤕', name: 'face with head-bandage', keywords: ['hurt', 'injury', 'accident'] },
      { emoji: '🤢', name: 'nauseated face', keywords: ['disgust', 'gross', 'sick'] },
      { emoji: '🤮', name: 'face vomiting', keywords: ['puke', 'gross', 'barf'] },
      { emoji: '🤧', name: 'sneezing face', keywords: ['sneeze', 'cold', 'flu'] },
      { emoji: '🥵', name: 'hot face', keywords: ['heat', 'summer', 'sweat', 'hot'] },
      { emoji: '🥶', name: 'cold face', keywords: ['freezing', 'winter', 'ice', 'cold'] },
      { emoji: '🥴', name: 'woozy face', keywords: ['drunk', 'dizzy', 'tired'] },
      { emoji: '😵', name: 'face with crossed-out eyes', keywords: ['dead', 'dizzy', 'shocked'] },
      { emoji: '😵‍💫', name: 'face with spiral eyes', keywords: ['hypnotized', 'dizzy', 'overwhelmed'] },
      { emoji: '🤯', name: 'exploding head', keywords: ['mindblown', 'shocked', 'boom', 'wow'] },
      { emoji: '🤠', name: 'cowboy hat face', keywords: ['cowboy', 'country', 'western'] },
      { emoji: '🥳', name: 'partying face', keywords: ['party', 'celebration', 'birthday', 'woo'] },
      { emoji: '🥸', name: 'disguised face', keywords: ['disguise', 'glasses', 'spy', 'incognito'] },
      { emoji: '😎', name: 'smiling face with sunglasses', keywords: ['cool', 'shades', 'boss', 'sun'] },
      { emoji: '🤓', name: 'nerd face', keywords: ['geek', 'nerd', 'smart', 'glasses'] },
      { emoji: '🧐', name: 'face with monocle', keywords: ['investigate', 'curious', 'smart'] },
      { emoji: '😕', name: 'confused face', keywords: ['confused', 'puzzled', 'huh'] },
      { emoji: '😟', name: 'worried face', keywords: ['worry', 'scared', 'nervous'] },
      { emoji: '🙁', name: 'slightly frowning face', keywords: ['sad', 'disappointed'] },
      { emoji: '☹️', name: 'frowning face', keywords: ['sad', 'unhappy', 'cry'] },
      { emoji: '😮', name: 'face with open mouth', keywords: ['gasp', 'wow', 'surprised'] },
      { emoji: '😯', name: 'hushed face', keywords: ['silence', 'surprise', 'quiet'] },
      { emoji: '😲', name: 'astonished face', keywords: ['shock', 'amazed', 'omg'] },
      { emoji: '😳', name: 'flushed face', keywords: ['blush', 'embarrassed', 'shy'] },
      { emoji: '🥺', name: 'pleading face', keywords: ['puppy', 'please', 'beg', 'cute'] },
      { emoji: '🥹', name: 'face holding back tears', keywords: ['proud', 'crying', 'moved', 'emotional'] },
      { emoji: '😦', name: 'frowning face with open mouth', keywords: ['shocked', 'sad'] },
      { emoji: '😧', name: 'anguished face', keywords: ['pain', 'shock'] },
      { emoji: '😨', name: 'fearful face', keywords: ['scared', 'fear', 'spooked'] },
      { emoji: '😰', name: 'anxious face with sweat', keywords: ['nervous', 'anxiety', 'worried'] },
      { emoji: '😥', name: 'sad but relieved face', keywords: ['sad', 'phew', 'relieved'] },
      { emoji: '😢', name: 'crying face', keywords: ['cry', 'sad', 'tear'] },
      { emoji: '😭', name: 'loudly crying face', keywords: ['sob', 'cry', 'sad', 'tears', 'bawling'] },
      { emoji: '😱', name: 'face screaming in fear', keywords: ['scream', 'scared', 'horror', 'omg'] },
      { emoji: '😖', name: 'confounded face', keywords: ['frustrated', 'struggle'] },
      { emoji: '😣', name: 'persevering face', keywords: ['persevere', 'endure', 'trying'] },
      { emoji: '😞', name: 'disappointed face', keywords: ['sad', 'fail', 'bummed'] },
      { emoji: '😓', name: 'downcast face with sweat', keywords: ['hard', 'tired', 'sweat'] },
      { emoji: '😩', name: 'weary face', keywords: ['tired', 'frustrated', 'stressed'] },
      { emoji: '😫', name: 'tired face', keywords: ['exhausted', 'done', 'sleep'] },
      { emoji: '🥱', name: 'yawning face', keywords: ['yawn', 'sleepy', 'bored'] },
      { emoji: '😤', name: 'face with steam from nose', keywords: ['triumph', 'angry', 'huff'] },
      { emoji: '😡', name: 'enraged face', keywords: ['mad', 'angry', 'rage'] },
      { emoji: '😠', name: 'angry face', keywords: ['angry', 'mad', 'grumpy'] },
      { emoji: '🤬', name: 'face with symbols on mouth', keywords: ['swear', 'cuss', 'angry', 'furious'] },
      { emoji: '😈', name: 'smiling face with horns', keywords: ['devil', 'evil', 'naughty'] },
      { emoji: '👿', name: 'angry face with horns', keywords: ['demon', 'devil', 'rage'] },
      { emoji: '💀', name: 'skull', keywords: ['dead', 'skeleton', 'danger', 'death', 'lol'] },
      { emoji: '☠️', name: 'skull and crossbones', keywords: ['poison', 'danger', 'pirate', 'dead'] },
      { emoji: '💩', name: 'pile of poo', keywords: ['poop', 'poo', 'crap', 'funny'] },
      { emoji: '🤡', name: 'clown face', keywords: ['clown', 'fool', 'joke', 'circus'] },
      { emoji: '👹', name: 'ogre', keywords: ['monster', 'demon', 'japanese'] },
      { emoji: '👺', name: 'goblin', keywords: ['mask', 'tengu', 'evil'] },
      { emoji: '👻', name: 'ghost', keywords: ['spooky', 'halloween', 'boo', 'ninja', 'stealth'] },
      { emoji: '👽', name: 'alien', keywords: ['ufo', 'extraterrestrial', 'space'] },
      { emoji: '👾', name: 'alien monster', keywords: ['arcade', 'game', 'space invader'] },
      { emoji: '🤖', name: 'robot', keywords: ['bot', 'ai', 'machine', 'tech'] },
      { emoji: '❤️', name: 'red heart', keywords: ['love', 'heart', 'romantic', 'like'] },
      { emoji: '🧡', name: 'orange heart', keywords: ['love', 'heart', 'warm'] },
      { emoji: '💛', name: 'yellow heart', keywords: ['love', 'friendship', 'gold'] },
      { emoji: '💚', name: 'green heart', keywords: ['love', 'nature', 'safe'] },
      { emoji: '💙', name: 'blue heart', keywords: ['love', 'peace', 'calm'] },
      { emoji: '💜', name: 'purple heart', keywords: ['love', 'luxury', 'royal'] },
      { emoji: '🖤', name: 'black heart', keywords: ['dark', 'goth', 'love'] },
      { emoji: '🤍', name: 'white heart', keywords: ['pure', 'peace', 'love'] },
      { emoji: '🤎', name: 'brown heart', keywords: ['warm', 'coffee', 'earth'] },
      { emoji: '💔', name: 'broken heart', keywords: ['heartbreak', 'sad', 'breakup'] },
      { emoji: '❤️‍🔥', name: 'heart on fire', keywords: ['passion', 'fire', 'hot', 'love'] },
      { emoji: '❤️‍🩹', name: 'mending heart', keywords: ['heal', 'recover', 'better'] },
      { emoji: '💖', name: 'sparkling heart', keywords: ['sparkle', 'love', 'glitter'] },
      { emoji: '💗', name: 'growing heart', keywords: ['love', 'pulse', 'crush'] },
      { emoji: '💓', name: 'beating heart', keywords: ['heartbeat', 'alive', 'love'] },
      { emoji: '💞', name: 'revolving hearts', keywords: ['love', 'sweet', 'romance'] },
      { emoji: '💕', name: 'two hearts', keywords: ['love', 'affection', 'bff'] },
      { emoji: '💘', name: 'heart with arrow', keywords: ['cupid', 'crush', 'fall in love'] },
      { emoji: '💝', name: 'heart with ribbon', keywords: ['gift', 'present', 'love'] },
      { emoji: '✨', name: 'sparkles', keywords: ['magic', 'shine', 'glow', 'clean', 'star'] },
      { emoji: '🔥', name: 'fire', keywords: ['lit', 'hot', 'flame', 'hype', 'speed'] },
      { emoji: '💥', name: 'collision', keywords: ['boom', 'explode', 'bang', 'crash'] },
      { emoji: '💯', name: 'hundred points', keywords: ['perfect', 'score', '100', 'full'] },
    ],
  },
  {
    id: 'people',
    name: 'People & Gestures',
    icon: 'hand-left-outline',
    emojis: [
      { emoji: '👋', name: 'waving hand', keywords: ['wave', 'hello', 'bye', 'hi'] },
      { emoji: '🤚', name: 'raised back of hand', keywords: ['backhand', 'stop'] },
      { emoji: '🖐️', name: 'hand with fingers splayed', keywords: ['five', 'high five'] },
      { emoji: '✋', name: 'raised hand', keywords: ['stop', 'high five', 'halt'] },
      { emoji: '🖖', name: 'vulcan salute', keywords: ['spock', 'star trek', 'peace'] },
      { emoji: '🫱', name: 'rightwards hand', keywords: ['hand', 'reach'] },
      { emoji: '🫲', name: 'leftwards hand', keywords: ['hand', 'reach'] },
      { emoji: '🫵', name: 'index pointing at the viewer', keywords: ['you', 'point', 'pick'] },
      { emoji: '👌', name: 'OK hand', keywords: ['perfect', 'good', 'agree', 'ok'] },
      { emoji: '🤌', name: 'pinched fingers', keywords: ['italian', 'chef kiss', 'what'] },
      { emoji: '🤏', name: 'pinching hand', keywords: ['tiny', 'small', 'little'] },
      { emoji: '✌️', name: 'victory hand', keywords: ['peace', 'victory', 'two'] },
      { emoji: '🤞', name: 'crossed fingers', keywords: ['luck', 'hope', 'wish'] },
      { emoji: '🫰', name: 'hand with index finger and thumb crossed', keywords: ['kpop', 'finger heart', 'love'] },
      { emoji: '🤟', name: 'love-you gesture', keywords: ['ily', 'love', 'rock'] },
      { emoji: '🤘', name: 'sign of the horns', keywords: ['rock on', 'metal', 'party'] },
      { emoji: '🤙', name: 'call me hand', keywords: ['shaka', 'hang loose', 'call', 'cool'] },
      { emoji: '👈', name: 'backhand index pointing left', keywords: ['left', 'point'] },
      { emoji: '👉', name: 'backhand index pointing right', keywords: ['right', 'point'] },
      { emoji: '👆', name: 'backhand index pointing up', keywords: ['up', 'look'] },
      { emoji: '🖕', name: 'middle finger', keywords: ['flip off', 'rude'] },
      { emoji: '👇', name: 'backhand index pointing down', keywords: ['down', 'look'] },
      { emoji: '☝️', name: 'index pointing up', keywords: ['one', 'first', 'question'] },
      { emoji: '👍', name: 'thumbs up', keywords: ['like', 'approve', 'yes', 'good', 'ok'] },
      { emoji: '👎', name: 'thumbs down', keywords: ['dislike', 'no', 'bad'] },
      { emoji: '✊', name: 'raised fist', keywords: ['power', 'solidarity', 'strength'] },
      { emoji: '👊', name: 'oncoming fist', keywords: ['fist bump', 'punch', 'bro'] },
      { emoji: '🤛', name: 'left-facing fist', keywords: ['bump', 'punch'] },
      { emoji: '🤜', name: 'right-facing fist', keywords: ['bump', 'punch'] },
      { emoji: '👏', name: 'clapping hands', keywords: ['applause', 'bravo', 'congrats'] },
      { emoji: '🙌', name: 'raising hands', keywords: ['praise', 'hooray', 'celebrate'] },
      { emoji: '👐', name: 'open hands', keywords: ['hug', 'open', 'welcome'] },
      { emoji: '🤲', name: 'palms up together', keywords: ['prayer', 'ask', 'give'] },
      { emoji: '🤝', name: 'handshake', keywords: ['deal', 'agree', 'meeting', 'friend'] },
      { emoji: '🙏', name: 'folded hands', keywords: ['pray', 'please', 'thank you', 'namaste', 'hope'] },
      { emoji: '✍️', name: 'writing hand', keywords: ['write', 'note', 'pen'] },
      { emoji: '💅', name: 'nail polish', keywords: ['slay', 'sassy', 'beauty', 'done'] },
      { emoji: '🤳', name: 'selfie', keywords: ['camera', 'photo', 'phone'] },
      { emoji: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle', 'gym', 'flex', 'power'] },
      { emoji: '👀', name: 'eyes', keywords: ['look', 'watch', 'peek', 'sus', 'spy', 'see'] },
      { emoji: '👁️', name: 'eye', keywords: ['look', 'vision', 'see'] },
      { emoji: '🗣️', name: 'speaking head', keywords: ['talk', 'shout', 'speak'] },
      { emoji: '👤', name: 'bust in silhouette', keywords: ['user', 'person', 'profile', 'member'] },
      { emoji: '👥', name: 'busts in silhouette', keywords: ['circle', 'group', 'team', 'family', 'members'] },
      { emoji: '🫂', name: 'people hugging', keywords: ['hug', 'care', 'friends', 'support'] },
      { emoji: '🏃‍♂️', name: 'man running', keywords: ['run', 'hurry', 'omw', 'fast', 'sprint'] },
      { emoji: '🏃‍♀️', name: 'woman running', keywords: ['run', 'hurry', 'omw', 'fast'] },
      { emoji: '🚶‍♂️', name: 'man walking', keywords: ['walk', 'pedestrian', 'stroll'] },
      { emoji: '🚶‍♀️', name: 'woman walking', keywords: ['walk', 'pedestrian'] },
      { emoji: '🧍', name: 'person standing', keywords: ['stand', 'waiting'] },
      { emoji: '🧎', name: 'person kneeling', keywords: ['kneel', 'rest'] },
      { emoji: '💃', name: 'woman dancing', keywords: ['dance', 'party', 'fun'] },
      { emoji: '🕺', name: 'man dancing', keywords: ['dance', 'party', 'groove'] },
      { emoji: '🧑‍🤝‍🧑', name: 'people holding hands', keywords: ['couple', 'friends', 'circle'] },
      { emoji: '👮‍♂️', name: 'police officer', keywords: ['police', 'cop', 'security', 'law'] },
      { emoji: '🕵️‍♂️', name: 'detective', keywords: ['spy', 'stealth', 'investigate', 'look'] },
      { emoji: '💂', name: 'guard', keywords: ['guard', 'protect', 'circleguard'] },
      { emoji: '👷', name: 'construction worker', keywords: ['work', 'build', 'helmet'] },
      { emoji: '👩‍⚕️', name: 'health worker', keywords: ['doctor', 'nurse', 'hospital', 'medical'] },
      { emoji: '🦸', name: 'superhero', keywords: ['hero', 'save', 'super'] },
    ],
  },
  {
    id: 'travel',
    name: 'Travel, Maps & Safety',
    icon: 'navigate-outline',
    emojis: [
      { emoji: '📍', name: 'round pushpin', keywords: ['location', 'pin', 'gps', 'map', 'spot', 'here'] },
      { emoji: '🗺️', name: 'world map', keywords: ['map', 'travel', 'navigation', 'world'] },
      { emoji: '🧭', name: 'compass', keywords: ['direction', 'navigate', 'explore', 'bearing'] },
      { emoji: '🚗', name: 'automobile', keywords: ['car', 'drive', 'trip', 'commute', 'driving'] },
      { emoji: '🚙', name: 'sport utility vehicle', keywords: ['suv', 'car', 'travel'] },
      { emoji: '🏎️', name: 'racing car', keywords: ['speed', 'fast', 'race', 'speeding'] },
      { emoji: '🚓', name: 'police car', keywords: ['police', 'emergency', 'cop', 'siren'] },
      { emoji: '🚑', name: 'ambulance', keywords: ['medical', 'hospital', 'emergency', 'rescue'] },
      { emoji: '🚒', name: 'fire engine', keywords: ['fire', 'truck', 'emergency'] },
      { emoji: '🚐', name: 'minibus', keywords: ['van', 'travel', 'bus'] },
      { emoji: '🛻', name: 'pickup truck', keywords: ['truck', 'car'] },
      { emoji: '🚚', name: 'delivery truck', keywords: ['delivery', 'shipping'] },
      { emoji: '🏍️', name: 'motorcycle', keywords: ['bike', 'ride', 'motorbike'] },
      { emoji: '🛵', name: 'motor scooter', keywords: ['scooter', 'vespa', 'delivery'] },
      { emoji: '🚲', name: 'bicycle', keywords: ['bike', 'ride', 'cycling'] },
      { emoji: '🛴', name: 'kick scooter', keywords: ['scooter', 'ride'] },
      { emoji: '🚨', name: 'police car light', keywords: ['siren', 'alert', 'emergency', 'sos', 'danger', 'alarm'] },
      { emoji: '🛡️', name: 'shield', keywords: ['security', 'guard', 'protect', 'safe', 'circleguard'] },
      { emoji: '⚡', name: 'high voltage', keywords: ['flash', 'fast', 'lightning', 'energy', 'power'] },
      { emoji: '🪫', name: 'low battery', keywords: ['battery', 'dead', 'charge', 'empty', 'power'] },
      { emoji: '🔋', name: 'battery', keywords: ['power', 'charge', 'full'] },
      { emoji: '⛽', name: 'fuel pump', keywords: ['gas', 'petrol', 'station'] },
      { emoji: '🛑', name: 'stop sign', keywords: ['stop', 'halt', 'red'] },
      { emoji: '🚦', name: 'traffic light', keywords: ['light', 'signal', 'drive'] },
      { emoji: '🚧', name: 'construction', keywords: ['barrier', 'roadwork', 'caution'] },
      { emoji: '🏁', name: 'chequered flag', keywords: ['finish', 'destination', 'arrived', 'done'] },
      { emoji: '🚩', name: 'triangular flag', keywords: ['flag', 'landmark', 'post'] },
      { emoji: '🏠', name: 'house', keywords: ['home', 'safe zone', 'residence', 'family'] },
      { emoji: '🏡', name: 'house with garden', keywords: ['home', 'suburbs', 'house'] },
      { emoji: '🏢', name: 'office building', keywords: ['work', 'job', 'business'] },
      { emoji: '🏫', name: 'school', keywords: ['education', 'college', 'study', 'class'] },
      { emoji: '🏥', name: 'hospital', keywords: ['doctor', 'emergency', 'medical'] },
      { emoji: '🏪', name: 'convenience store', keywords: ['shop', 'store', 'market'] },
      { emoji: '🏨', name: 'hotel', keywords: ['stay', 'vacation', 'trip'] },
      { emoji: '✈️', name: 'airplane', keywords: ['flight', 'travel', 'trip', 'airport'] },
      { emoji: '🛫', name: 'airplane departure', keywords: ['takeoff', 'leave', 'fly'] },
      { emoji: '🛬', name: 'airplane arrival', keywords: ['landing', 'arrived', 'touchdown'] },
      { emoji: '🚀', name: 'rocket', keywords: ['speed', 'launch', 'fast', 'space', 'omw'] },
      { emoji: '🛸', name: 'flying saucer', keywords: ['ufo', 'alien', 'mystery'] },
      { emoji: '🚁', name: 'helicopter', keywords: ['chopper', 'air', 'fly'] },
      { emoji: '🚆', name: 'train', keywords: ['rail', 'transit', 'subway'] },
      { emoji: '🚇', name: 'metro', keywords: ['subway', 'tube', 'transit'] },
      { emoji: '🛳️', name: 'passenger ship', keywords: ['cruise', 'boat', 'ocean'] },
      { emoji: '🏖️', name: 'beach with umbrella', keywords: ['beach', 'vacation', 'ocean', 'summer'] },
      { emoji: '🏔️', name: 'snow-capped mountain', keywords: ['mountain', 'hike', 'nature'] },
      { emoji: '⛺', name: 'tent', keywords: ['camp', 'outdoor', 'nature'] },
    ],
  },
  {
    id: 'food',
    name: 'Food & Drink',
    icon: 'fast-food-outline',
    emojis: [
      { emoji: '🍕', name: 'pizza', keywords: ['food', 'cheese', 'slice', 'dinner'] },
      { emoji: '🍔', name: 'hamburger', keywords: ['burger', 'fast food', 'beef'] },
      { emoji: '🍟', name: 'french fries', keywords: ['fries', 'chips', 'snack'] },
      { emoji: '🌭', name: 'hot dog', keywords: ['sausage', 'snack'] },
      { emoji: '🍿', name: 'popcorn', keywords: ['movie', 'snack', 'drama'] },
      { emoji: '🥪', name: 'sandwich', keywords: ['lunch', 'bread'] },
      { emoji: '🌮', name: 'taco', keywords: ['mexican', 'food'] },
      { emoji: '🌯', name: 'burrito', keywords: ['wrap', 'mexican'] },
      { emoji: '🥙', name: 'stuffed flatbread', keywords: ['gyro', 'shawarma', 'falafel'] },
      { emoji: '🍝', name: 'spaghetti', keywords: ['pasta', 'italian', 'noodles'] },
      { emoji: '🍜', name: 'steaming bowl', keywords: ['ramen', 'noodles', 'soup'] },
      { emoji: '🍲', name: 'pot of food', keywords: ['stew', 'curry', 'soup'] },
      { emoji: '🍛', name: 'curry rice', keywords: ['curry', 'indian', 'dinner'] },
      { emoji: '🍣', name: 'sushi', keywords: ['japanese', 'fish', 'rice'] },
      { emoji: '🍱', name: 'bento box', keywords: ['lunch', 'japanese'] },
      { emoji: '🥟', name: 'dumpling', keywords: ['dim sum', 'chinese'] },
      { emoji: '🍦', name: 'soft ice cream', keywords: ['ice cream', 'dessert', 'sweet'] },
      { emoji: '🍧', name: 'shaved ice', keywords: ['dessert', 'cold', 'sweet'] },
      { emoji: '🍨', name: 'ice cream', keywords: ['dessert', 'gelato', 'sweet'] },
      { emoji: '🍩', name: 'doughnut', keywords: ['donut', 'sweet', 'bakery'] },
      { emoji: '🍪', name: 'cookie', keywords: ['biscuit', 'chocolate chip', 'sweet'] },
      { emoji: '🎂', name: 'birthday cake', keywords: ['cake', 'celebration', 'party'] },
      { emoji: '🍰', name: 'shortcake', keywords: ['cake', 'slice', 'dessert'] },
      { emoji: '🧁', name: 'cupcake', keywords: ['sweet', 'bakery'] },
      { emoji: '🍫', name: 'chocolate bar', keywords: ['candy', 'sweet'] },
      { emoji: '🍬', name: 'candy', keywords: ['sweet', 'sugar'] },
      { emoji: '🍭', name: 'lollipop', keywords: ['candy', 'sweet'] },
      { emoji: '☕', name: 'hot beverage', keywords: ['coffee', 'tea', 'cafe', 'morning'] },
      { emoji: '🧋', name: 'bubble tea', keywords: ['boba', 'tea', 'milk tea'] },
      { emoji: '🍵', name: 'teacup without handle', keywords: ['green tea', 'matcha'] },
      { emoji: '🥤', name: 'cup with straw', keywords: ['soda', 'drink', 'juice'] },
      { emoji: '🧃', name: 'beverage box', keywords: ['juice box', 'drink'] },
      { emoji: '🍺', name: 'beer mug', keywords: ['beer', 'drink', 'pub', 'cheers'] },
      { emoji: '🍻', name: 'clinking beer mugs', keywords: ['cheers', 'beers', 'party'] },
      { emoji: '🥂', name: 'clinking glasses', keywords: ['champagne', 'toast', 'celebrate'] },
      { emoji: '🍷', name: 'wine glass', keywords: ['wine', 'drink', 'dinner'] },
      { emoji: '🥃', name: 'tumbler glass', keywords: ['whiskey', 'liquor', 'bourbon'] },
      { emoji: '🍸', name: 'cocktail glass', keywords: ['martini', 'bar', 'drink'] },
      { emoji: '🍹', name: 'tropical drink', keywords: ['cocktail', 'vacation', 'summer'] },
      { emoji: '🍎', name: 'red apple', keywords: ['fruit', 'healthy', 'food'] },
      { emoji: '🍌', name: 'banana', keywords: ['fruit', 'snack'] },
      { emoji: '🍉', name: 'watermelon', keywords: ['fruit', 'summer'] },
      { emoji: '🍇', name: 'grapes', keywords: ['fruit', 'wine'] },
      { emoji: '🍓', name: 'strawberry', keywords: ['fruit', 'berry'] },
      { emoji: '🥑', name: 'avocado', keywords: ['guacamole', 'healthy'] },
    ],
  },
  {
    id: 'animals',
    name: 'Animals & Nature',
    icon: 'paw-outline',
    emojis: [
      { emoji: '🐶', name: 'dog face', keywords: ['puppy', 'pet', 'doggo'] },
      { emoji: '🐱', name: 'cat face', keywords: ['kitty', 'kitten', 'pet', 'meow'] },
      { emoji: '🐭', name: 'mouse face', keywords: ['rat', 'rodent'] },
      { emoji: '🐹', name: 'hamster', keywords: ['pet', 'cute'] },
      { emoji: '🐰', name: 'rabbit face', keywords: ['bunny', 'cute', 'pet'] },
      { emoji: '🦊', name: 'fox', keywords: ['sly', 'wild'] },
      { emoji: '🐻', name: 'bear', keywords: ['grizzly', 'wild', 'teddy'] },
      { emoji: '🐼', name: 'panda', keywords: ['cute', 'bamboo'] },
      { emoji: '🐨', name: 'koala', keywords: ['australia', 'cute'] },
      { emoji: '🐯', name: 'tiger face', keywords: ['wild', 'cat', 'rawr'] },
      { emoji: '🦁', name: 'lion', keywords: ['king', 'wild', 'rawr', 'brave'] },
      { emoji: '🐮', name: 'cow face', keywords: ['moo', 'farm'] },
      { emoji: '🐷', name: 'pig face', keywords: ['oink', 'farm'] },
      { emoji: '🐸', name: 'frog', keywords: ['toad', 'pepe', 'ribbit'] },
      { emoji: '🐵', name: 'monkey face', keywords: ['chimp', 'silly'] },
      { emoji: '🐔', name: 'chicken', keywords: ['rooster', 'bird', 'farm'] },
      { emoji: '🐧', name: 'penguin', keywords: ['antarctica', 'cold', 'bird'] },
      { emoji: '🐦', name: 'bird', keywords: ['fly', 'nature'] },
      { emoji: '🦅', name: 'eagle', keywords: ['bird', 'freedom', 'fly'] },
      { emoji: '🦉', name: 'owl', keywords: ['night', 'wise', 'bird'] },
      { emoji: '🦇', name: 'bat', keywords: ['spooky', 'night', 'vampire'] },
      { emoji: '🐺', name: 'wolf', keywords: ['pack', 'howl', 'wild'] },
      { emoji: '🦄', name: 'unicorn', keywords: ['magic', 'fantasy', 'horse'] },
      { emoji: '🐝', name: 'honeybee', keywords: ['bee', 'buzz', 'honey'] },
      { emoji: '🐛', name: 'bug', keywords: ['caterpillar', 'insect'] },
      { emoji: '🦋', name: 'butterfly', keywords: ['pretty', 'nature', 'wings'] },
      { emoji: '🌸', name: 'cherry blossom', keywords: ['flower', 'pink', 'spring', 'sakura'] },
      { emoji: '🌹', name: 'rose', keywords: ['flower', 'red', 'romance', 'love'] },
      { emoji: '🌻', name: 'sunflower', keywords: ['flower', 'summer', 'sun'] },
      { emoji: '🌲', name: 'evergreen tree', keywords: ['tree', 'forest', 'nature', 'pine'] },
      { emoji: '🌴', name: 'palm tree', keywords: ['beach', 'tropical', 'vacation'] },
      { emoji: '🍀', name: 'four leaf clover', keywords: ['lucky', 'luck', 'irish', 'green'] },
      { emoji: '🍁', name: 'maple leaf', keywords: ['autumn', 'fall', 'canada'] },
      { emoji: '☀️', name: 'sun', keywords: ['sunny', 'weather', 'bright', 'day'] },
      { emoji: '🌙', name: 'crescent moon', keywords: ['night', 'sleep', 'dark', 'moon'] },
      { emoji: '⭐', name: 'star', keywords: ['gold', 'favorite', 'night', 'shine'] },
      { emoji: '⚡', name: 'zap', keywords: ['lightning', 'thunder', 'storm', 'power'] },
      { emoji: '🌈', name: 'rainbow', keywords: ['pride', 'color', 'nature'] },
      { emoji: '🌧️', name: 'cloud with rain', keywords: ['rain', 'weather', 'storm'] },
      { emoji: '❄️', name: 'snowflake', keywords: ['cold', 'snow', 'winter', 'ice'] },
    ],
  },
  {
    id: 'objects',
    name: 'Objects & Symbols',
    icon: 'cube-outline',
    emojis: [
      { emoji: '📱', name: 'mobile phone', keywords: ['iphone', 'android', 'cell', 'call', 'screen'] },
      { emoji: '💻', name: 'laptop', keywords: ['computer', 'macbook', 'work', 'code'] },
      { emoji: '⌚', name: 'watch', keywords: ['time', 'apple watch', 'clock'] },
      { emoji: '⏰', name: 'alarm clock', keywords: ['time', 'morning', 'wake up', 'late'] },
      { emoji: '🔑', name: 'key', keywords: ['lock', 'door', 'access', 'secret'] },
      { emoji: '🔒', name: 'locked', keywords: ['secure', 'privacy', 'safe', 'lock'] },
      { emoji: '🔓', name: 'unlocked', keywords: ['open', 'free'] },
      { emoji: '💰', name: 'money bag', keywords: ['cash', 'dollar', 'rich', 'wealth'] },
      { emoji: '💳', name: 'credit card', keywords: ['payment', 'buy', 'money'] },
      { emoji: '💎', name: 'gem stone', keywords: ['diamond', 'luxury', 'precious', 'jewelry'] },
      { emoji: '💡', name: 'light bulb', keywords: ['idea', 'bright', 'smart', 'think'] },
      { emoji: '📦', name: 'package', keywords: ['box', 'delivery', 'amazon', 'parcel'] },
      { emoji: '🎁', name: 'wrapped gift', keywords: ['present', 'birthday', 'surprise'] },
      { emoji: '🎉', name: 'party popper', keywords: ['tada', 'celebrate', 'congrats', 'party'] },
      { emoji: '🎊', name: 'confetti ball', keywords: ['party', 'celebration'] },
      { emoji: '🏆', name: 'trophy', keywords: ['winner', 'champion', 'first', 'gold'] },
      { emoji: '🥇', name: '1st place medal', keywords: ['gold', 'first', 'winner'] },
      { emoji: '⚽', name: 'soccer ball', keywords: ['football', 'sport', 'game'] },
      { emoji: '🏀', name: 'basketball', keywords: ['sport', 'nba', 'ball'] },
      { emoji: '🎮', name: 'video game', keywords: ['gaming', 'controller', 'playstation', 'xbox'] },
      { emoji: '🎧', name: 'headphone', keywords: ['music', 'audio', 'sound', 'listen'] },
      { emoji: '📷', name: 'camera', keywords: ['photo', 'picture', 'snapshot'] },
      { emoji: '🔔', name: 'bell', keywords: ['notification', 'alert', 'ring'] },
      { emoji: '🔕', name: 'bell with slash', keywords: ['mute', 'silent', 'quiet'] },
      { emoji: '📣', name: 'megaphone', keywords: ['announcement', 'shout', 'broadcast'] },
      { emoji: '⚠️', name: 'warning', keywords: ['caution', 'danger', 'alert', 'watch out'] },
      { emoji: '⛔', name: 'no entry', keywords: ['forbidden', 'stop', 'restricted'] },
      { emoji: '✅', name: 'check mark button', keywords: ['yes', 'verified', 'approved', 'done', 'ok'] },
      { emoji: '❌', name: 'cross mark', keywords: ['no', 'cancel', 'wrong', 'x'] },
      { emoji: '❓', name: 'question mark', keywords: ['what', 'confused', 'help'] },
      { emoji: '❗', name: 'exclamation mark', keywords: ['urgent', 'important', 'alert'] },
      { emoji: '💬', name: 'speech balloon', keywords: ['chat', 'message', 'text', 'talk'] },
      { emoji: '💭', name: 'thought balloon', keywords: ['thinking', 'dream', 'idea'] },
    ],
  },
];
